version: '3.5'

services:
    web:
        build: .
        command: gunicorn web.wsgi:application -w 4 --bind 0.0.0.0:8000
        volumes:
            #- ./:/usr/src/app/
            - static_volume:/usr/src/app/staticfiles
        expose:
            - 8000
        environment:
            - SECRET_KEY=
            - SQL_ENGINE=django.db.backends.postgresql
            - SQL_DATABASE=postgres
            - SQL_USER=
            - SQL_PASSWORD=
            - SQL_HOST=db
            - SQL_PORT=5432
            - DATABASE=postgres
            - ALLOWED_HOST=localhost
            - DEBUG=False
        depends_on:
            - db

    db:
        image: postgres:10.5-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=
            - POSTGRES_PASSWORD=

    nginx:
        build: ./nginx
        ports:
            - 1337:80
        depends_on:
            - web
        volumes:
            - static_volume:/usr/src/app/staticfiles

volumes:
    postgres_data:
    static_volume:
